In [3]:
pip install yfinance

Collecting yfinance
  Downloading yfinance-1.4.1-py2.py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pandas>=1.3.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: requests>=2.31 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (2.34.2)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: platformdirs>=2.0.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (2026.2)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.1.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (4.12.3)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.15.0-cp310-abi3-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: protobuf>=3.19.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from yfinance) (6.33.5)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-16.0-cp313-cp313-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: soupsieve>1.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.5.20)
Requirement already satisfied: rich in C:\Users\mcm4g\anaconda3\Lib\site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: pycparser in C:\Users\mcm4g\anaconda3\Lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.31->yfinance) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Downloading yfinance-1.4.1-py2.py3-none-any.whl (137 kB)
Downloading curl_cffi-0.15.0-cp310-abi3-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 18.0 MB/s  0:00:00
Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.1.0-py3-none-any.whl (155 kB)
Downloading websockets-16.0-cp313-cp313-win_amd64.whl (178 kB)
Installing collected packages: peewee, multitasking, websockets, curl_cffi, yfinance

   ---------------------------------------- 0/5 [peewee]
   ---------------- ----------------------- 2/5 [websockets]
   ------------------------ --------------- 3/5 [curl_cffi]
   -------------------------------- ------- 4/5 [yfinance]
   ---------------------------------------- 5/5 [yfinance]

Successfully installed curl_cffi-0.15.0 multitasking-0.0.13 peewee-4.1.0 websockets-16.0 yfinance-1.4.1
Note: you may need to restart the kernel to use updated packages.

In [113]:
import yfinance as yf
import numpy as np
import pandas as pd
import talib

In [114]:
# import data from ticker 

ydf = yf.download("NVDA",
                  start="2015-01-01",
                  end="2026-04-30",
                  progress=False)

In [115]:
print(f"Downloaded {len(ydf)} rows of data.")

Downloaded 2847 rows of data.

In [116]:
ydf

Price            Close        High         Low        Open     Volume
Ticker            NVDA        NVDA        NVDA        NVDA       NVDA
Date
2015-01-02    0.482423    0.486018    0.474754    0.482423  113680000
2015-01-05    0.474275    0.483861    0.472118    0.482423  197952000
2015-01-06    0.459895    0.475473    0.459416    0.474994  197764000
2015-01-07    0.458697    0.467325    0.457259    0.463251  321808000
2015-01-08    0.475952    0.478828    0.463730    0.463970  283780000
...                ...         ...         ...         ...        ...
2026-04-23  199.407593  203.592718  196.990412  202.224317  113561800
2026-04-24  208.027542  210.704415  199.577384  199.727219  214134400
2026-04-27  216.357834  216.577579  207.138583  209.405930  187172400
2026-04-28  212.921844  214.480026  207.957629  209.246136  180275400
2026-04-29  209.006409  212.472370  207.338355  212.452389  123711800

[2847 rows x 5 columns]

In [117]:
ydf.columns

MultiIndex([( 'Close', 'NVDA'),
            (  'High', 'NVDA'),
            (   'Low', 'NVDA'),
            (  'Open', 'NVDA'),
            ('Volume', 'NVDA')],
           names=['Price', 'Ticker'])

In [118]:
# Create column for the length of the candle body and daily price action (Total candle range)
ydf['Candle_Body'] = (ydf[('Close', 'NVDA')] - ydf[('Open', 'NVDA')]).abs()
ydf['Total price action'] = (ydf[('High', 'NVDA')] - ydf[('Low', 'NVDA')])

# Create a column to determine if Candle is bullish, bearish or a doji
doji = abs(ydf['Close', 'NVDA'] - ydf['Open', 'NVDA']) <= (0.10 * (ydf['High', 'NVDA'] - ydf['Close', 'NVDA']))
ydf['Bullish/Bearish'] = np.where(
    doji,
    'Doji',
    np.where((ydf['Close', 'NVDA'] > ydf['Open', 'NVDA']), 'Bullish', 'Bearish')
)

# Create column for candle body percentage by dividing the candle body by the total price action of the day
ydf['Body %'] = (ydf['Candle_Body'] / ydf['Total price action']) * 100

# Change total price action column to Candle_range 

ydf = ydf.rename(columns={'Total price action': 'Candle_Range'})

ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_Range,Bullish/Bearish,Body %
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,
Date,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Doji,0.000000
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,69.387800
2015-01-06,0.459895,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,94.029920
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,45.237879
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,79.364899
...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,42.662739
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,74.596032
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,73.650888
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,56.355182
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,67.120571

In [119]:
ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_Range,Bullish/Bearish,Body %
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,
Date,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Doji,0.000000
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,69.387800
2015-01-06,0.459895,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,94.029920
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,45.237879
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,79.364899
...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,42.662739
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,74.596032
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,73.650888
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,56.355182
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,67.120571

In [120]:
#Add 5, 10, 20, 50, and 200 day EMA Columns 

ydf['5_EMA'] = ydf['Close', 'NVDA'].ewm(span=5, adjust=False).mean()
ydf['10_EMA'] = ydf['Close', 'NVDA'].ewm(span=10, adjust=False).mean()
ydf['20_EMA'] = ydf['Close', 'NVDA'].ewm(span=20, adjust=False).mean()
ydf['50_EMA'] = ydf['Close', 'NVDA'].ewm(span=50, adjust=False).mean()
ydf['200_EMA'] = ydf['Close', 'NVDA'].ewm(span=20, adjust=False).mean()

ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_Range,Bullish/Bearish,Body %,5_EMA,10_EMA,20_EMA,50_EMA,200_EMA
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,,,,,,
Date,,,,,,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Doji,0.000000,0.482423,0.482423,0.482423,0.482423,0.482423
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,69.387800,0.479707,0.480942,0.481647,0.482104,0.481647
2015-01-06,0.459895,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,94.029920,0.473103,0.477115,0.479575,0.481233,0.479575
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,45.237879,0.468301,0.473766,0.477587,0.480349,0.477587
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,79.364899,0.470852,0.474164,0.477431,0.480177,0.477431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,42.662739,199.743683,196.414477,190.964749,186.173520,190.964749
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,74.596032,202.504969,198.525943,192.589777,187.030540,192.589777
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,73.650888,207.122591,201.768105,194.853401,188.180630,194.853401
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,56.355182,209.055675,203.796058,196.574205,189.150874,196.574205
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,67.120571,209.039253,204.743394,197.758225,189.929522,197.758225

In [121]:
pip install TA-lib

Requirement already satisfied: TA-lib in C:\Users\mcm4g\anaconda3\Lib\site-packages (0.6.8)
Requirement already satisfied: build in C:\Users\mcm4g\anaconda3\Lib\site-packages (from TA-lib) (1.5.0)
Requirement already satisfied: numpy in C:\Users\mcm4g\anaconda3\Lib\site-packages (from TA-lib) (2.4.6)
Requirement already satisfied: packaging>=24.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from build->TA-lib) (26.0)
Requirement already satisfied: pyproject_hooks in C:\Users\mcm4g\anaconda3\Lib\site-packages (from build->TA-lib) (1.2.0)
Requirement already satisfied: colorama in C:\Users\mcm4g\anaconda3\Lib\site-packages (from build->TA-lib) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [122]:
import talib

In [123]:
ydf['RSI'] = talib.RSI(ydf['Close', 'NVDA'])
ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_Range,Bullish/Bearish,Body %,5_EMA,10_EMA,20_EMA,50_EMA,200_EMA,RSI
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,,,,,,,
Date,,,,,,,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Doji,0.000000,0.482423,0.482423,0.482423,0.482423,0.482423,NaN
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,69.387800,0.479707,0.480942,0.481647,0.482104,0.481647,NaN
2015-01-06,0.459895,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,94.029920,0.473103,0.477115,0.479575,0.481233,0.479575,NaN
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,45.237879,0.468301,0.473766,0.477587,0.480349,0.477587,NaN
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,79.364899,0.470852,0.474164,0.477431,0.480177,0.477431,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,42.662739,199.743683,196.414477,190.964749,186.173520,190.964749,64.645029
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,74.596032,202.504969,198.525943,192.589777,187.030540,192.589777,71.498286
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,73.650888,207.122591,201.768105,194.853401,188.180630,194.853401,76.282913
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,56.355182,209.055675,203.796058,196.574205,189.150874,196.574205,70.989367
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,67.120571,209.039253,204.743394,197.758225,189.929522,197.758225,65.418380

In [133]:
#Calculate the upper wick by subtracking the high from either the open or close. Use max function and axis=1 to choose the option closest to the upperwick
ydf['Upper_wick'] = abs(ydf['High', 'NVDA'] - ydf[[('Open', 'NVDA'), ('Close', 'NVDA')]].max(axis=1))
# Caculate the same for the lower wick using the min function with axis=1 so it chooses the value closest to the lower wick between the open and close
ydf['Lower_wick'] = abs(ydf['Low', 'NVDA'] - ydf[[('Open', 'NVDA'), ('Close', 'NVDA')]].min(axis=1))

# Calculate wick percentage by dividing the absolute value of the upper or lower wick by the candle ranage (total candle length)
ydf['Upper_wick_percentage'] = abs(ydf['Upper_wick'] / ydf['Candle_Range']) * 100
ydf['Lower_wick_percentage'] = abs(ydf['Lower_wick'] / ydf['Candle_Range']) * 100

# Calculate Wick to body ratio by dividing the sum of the wicks by the candle body
ydf['Wick_to_body_ratio'] = (ydf['Lower_wick'] + ydf['Upper_wick']) / ydf['Candle_Body']

# Calsulate the gap size 
ydf['gap_size'] = ydf['Open', 'NVDA'] - ydf['Close', 'NVDA'].shift(1)
# Calculate gap percentage 
ydf['gap_percentage'] = (ydf['gap_size'] / ydf['Close', 'NVDA'].shift(1)) * 

ydf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_Range,Bullish/Bearish,Body %,5_EMA,...,50_EMA,200_EMA,RSI,Upper_wick,Lower_wick,Upper_wick_percentage,Lower_wick_percentage,Wick_to_body_ratio,gap_size,gap_percentage
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,,,...,,,,,,,,,,
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Doji,0.000000,0.482423,...,0.482423,0.482423,NaN,0.003595,0.007669,31.915002,68.084998,inf,NaN,NaN
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,69.387800,0.479707,...,0.482104,0.481647,NaN,0.001438,0.002157,12.244977,18.367223,0.441176,-4.504518e-08,-9.337276e-08
2015-01-06,0.459895,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,94.029920,0.473103,...,0.481233,0.479575,NaN,0.000479,0.000479,2.985040,2.985040,0.063491,7.188530e-04,1.515689e-03
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,45.237879,0.468301,...,0.480349,0.477587,NaN,0.004074,0.001438,40.476326,14.285795,1.210537,3.355263e-03,7.295708e-03
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,79.364899,0.470852,...,0.480177,0.477431,NaN,0.002876,0.000240,19.047727,1.587374,0.260003,5.272332e-03,1.149414e-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,42.662739,199.743683,...,186.173520,190.964749,64.645029,1.368400,2.417181,20.726097,36.611164,1.343966,-3.994972e-02,-1.975125e-04
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,74.596032,202.504969,...,187.030540,192.589777,71.498286,2.676873,0.149835,24.057386,1.346581,0.340554,3.196261e-01,1.602878e-03
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,73.650888,207.122591,...,188.180630,194.853401,76.282913,0.219745,2.267346,2.328056,24.021056,0.357757,1.378388e+00,6.625986e-03
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,56.355182,209.055675,...,189.150874,196.574205,70.989367,1.558182,1.288507,23.889707,19.755112,0.774460,-7.111698e+00,-3.287007e-02
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,67.120571,209.039253,...,189.929522,197.758225,65.418380,0.019981,1.668054,0.389188,32.490241,0.489856,-4.694550e-01,-2.204823e-03

In [130]:
ydf.iloc[1500:1550]

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_Range,Bullish/Bearish,Body %,5_EMA,10_EMA,20_EMA,50_EMA,200_EMA,RSI,Upper_wick,Lower_wick,Upper_wick_percentage,Lower_wick_percentage
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,,,,,,,,,,,
Date,,,,,,,,,,,,,,,,,,,
2020-12-16,13.189279,13.383246,13.159398,13.368555,223116000,0.179276,0.223847,Bearish,80.088514,13.189369,13.200899,13.232207,13.142336,13.232207,48.964616,0.014691,0.029880,6.563046,13.348439
2020-12-17,13.287631,13.325727,13.125535,13.313028,231384000,0.025397,0.200192,Bearish,12.686227,13.222123,13.216668,13.237486,13.148034,13.237486,50.906178,0.012699,0.162096,6.343588,80.970185
2020-12-18,13.218658,13.351123,13.017968,13.325228,342064000,0.106569,0.333155,Bearish,31.987923,13.220968,13.217030,13.235693,13.150803,13.235693,49.484424,0.025896,0.200690,7.772817,60.239260
2020-12-21,13.278665,13.316263,12.915381,13.022200,302332000,0.256465,0.400882,Bullish,63.975055,13.240200,13.228236,13.239785,13.155817,13.239785,50.772569,0.037599,0.106819,9.378939,26.646006
2020-12-22,13.224883,13.283646,13.001535,13.265719,185580000,0.040836,0.282111,Bearish,14.474982,13.235094,13.227627,13.238366,13.158526,13.238366,49.552931,0.017927,0.223349,6.354690,79.170328
2020-12-23,12.956964,13.221645,12.952731,13.202722,179144000,0.245758,0.268914,Bearish,91.389012,13.142384,13.178415,13.211566,13.150621,13.211566,43.895977,0.018924,0.004232,7.037070,1.573919
2020-12-24,12.941527,13.079720,12.886749,12.984852,97884000,0.043325,0.192971,Bearish,22.451652,13.075432,13.135345,13.185848,13.142422,13.185848,43.587237,0.094867,0.054778,49.161502,28.386846
2020-12-28,12.848153,13.010000,12.711953,13.010000,212564000,0.161847,0.298047,Bearish,54.302614,12.999672,13.083128,13.153686,13.130882,13.153686,41.677634,0.000000,0.136200,0.000000,45.697386
2020-12-29,12.891229,13.019960,12.790635,12.873053,170372000,0.018176,0.229325,Bullish,7.925943,12.963524,13.048237,13.128690,13.121484,13.128690,42.920019,0.128731,0.082418,56.134777,35.939280
2020-12-30,13.092917,13.160644,12.844919,12.938042,225396000,0.154875,0.315725,Bullish,49.053845,13.006655,13.056361,13.125283,13.120363,13.125283,48.456459,0.067727,0.093123,21.451092,29.495063
2020-12-31,13.002532,13.098146,12.863094,13.083705,192424000,0.081173,0.235052,Bearish,34.533912,13.005281,13.046574,13.113593,13.115742,13.113593,46.289596,0.014441,0.139438,6.143924,59.322164
2021-01-04,13.060799,13.597633,12.910405,13.051586,560640000,0.009213,0.687228,Doji,1.340533,13.023787,13.049160,13.108565,13.113588,13.108565,47.906808,0.536834,0.141181,78.115956,20.543511
2021-01-05,13.350875,13.389469,13.034402,13.047100,322760000,0.303774,0.355067,Bullish,85.554162,13.132816,13.104017,13.131642,13.122893,13.131642,55.147388,0.038594,0.012698,10.869490,3.576349
2021-01-06,12.563803,13.191769,12.535418,13.169359,580424000,0.605556,0.656351,Bearish,92.261049,12.943145,13.005797,13.077562,13.100968,13.077562,39.218892,0.022410,0.028385,3.414273,4.324678
2021-01-07,13.290368,13.323983,12.834707,12.915381,461480000,0.374987,0.489276,Bullish,76.641242,13.058886,13.057537,13.097829,13.108396,13.097829,52.778191,0.033615,0.080674,6.870337,16.488421
2021-01-08,13.223388,13.367058,12.989581,13.308794,292528000,0.085406,0.377476,Bearish,22.625500,13.113720,13.087692,13.109787,13.112905,13.109787,51.634610,0.058264,0.233806,15.435193,61.939307
2021-01-11,13.566756,13.904892,13.308797,13.364821,518344000,0.201935,0.596095,Bullish,33.876378,13.264732,13.174794,13.153308,13.130703,13.153308,56.802028,0.338136,0.056024,56.725194,9.398429
2021-01-12,13.430552,13.699219,13.291365,13.697226,291476000,0.266674,0.407854,Bearish,65.384544,13.320006,13.221296,13.179712,13.142462,13.179712,54.322702,0.001993,0.139188,0.488598,34.126858
2021-01-13,13.477365,13.570241,13.331206,13.435783,210028000,0.041582,0.239035,Bullish,17.395831,13.372459,13.267854,13.208060,13.155595,13.208060,55.048928,0.092876,0.104578,38.854318,43.749851
2021-01-14,13.147198,13.545092,13.127527,13.520442,283120000,0.373244,0.417565,Bearish,89.385940,13.297372,13.245916,13.202264,13.155266,13.202264,49.117485,0.024650,0.019670,5.903347,4.710713
2021-01-15,12.807817,13.271694,12.796861,13.174835,277780000,0.367019,0.474833,Bearish,77.294222,13.134187,13.166262,13.164697,13.141641,13.164697,43.883305,0.096859,0.010955,20.398553,2.307225
2021-01-19,12.972899,13.041373,12.792377,12.963935,226188000,0.008965,0.248995,Bullish,3.600311,13.080424,13.131105,13.146431,13.135023,13.146431,46.850271,0.068473,0.171557,27.499771,68.899918
2021-01-20,13.312033,13.376522,13.004275,13.059053,258572000,0.252980,0.372248,Bullish,67.960092,13.157627,13.164001,13.162203,13.141965,13.162203,52.416142,0.064489,0.054778,17.324352,14.715556
2021-01-21,13.811767,13.942987,13.199736,13.364571,337780000,0.447196,0.743251,Bullish,60.167540,13.375674,13.281777,13.224066,13.168232,13.224066,59.196901,0.131221,0.164835,17.654952,22.177508
2021-01-22,13.657388,13.786119,13.572480,13.684777,246820000,0.027390,0.213638,Bearish,12.820558,13.469578,13.350069,13.265335,13.187414,13.265335,56.517514,0.101341,0.084907,47.435977,39.743464
2021-01-25,13.598375,13.772921,13.183300,13.726359,251112000,0.127984,0.589621,Bearish,21.706078,13.512511,13.395216,13.297053,13.203530,13.297053,55.483701,0.046562,0.415075,7.896971,70.396951
2021-01-26,13.381252,13.589910,13.333694,13.525918,163980000,0.144666,0.256216,Bearish,56.462376,13.468758,13.392677,13.305072,13.210500,13.305072,51.734115,0.063992,0.047559,24.975718,18.561906
2021-01-27,12.865832,13.179566,12.742330,13.176827,371272000,0.310994,0.437236,Bearish,71.127356,13.267783,13.296887,13.263239,13.196983,13.263239,44.112911,0.002739,0.123502,0.626514,28.246130
2021-01-28,12.998544,13.286134,12.908408,12.944014,228316000,0.054529,0.377726,Bullish,14.436233,13.178036,13.242643,13.238030,13.189201,13.238030,46.306232,0.287590,0.035607,76.137178,9.426589
2021-01-29,12.937543,13.281157,12.859607,13.022450,271552000,0.084907,0.421549,Bearish,20.141727,13.097872,13.187170,13.209412,13.179333,13.209412,45.423790,0.258706,0.077935,61.370406,18.487866
2021-02-01,13.183799,13.217413,12.850892,13.000787,217204000,0.183012,0.366521,Bullish,49.932103,13.126514,13.186557,13.206973,13.179508,13.206973,49.599383,0.033614,0.149895,9.171081,40.896817
2021-02-02,13.502263,13.517451,13.232103,13.344898,220440000,0.157365,0.285348,Bullish,55.148344,13.251764,13.243958,13.235096,13.192165,13.235096,54.452675,0.015188,0.112796,5.322602,39.529055
2021-02-03,13.476121,13.875758,13.462177,13.581196,245408000,0.105075,0.413581,Bearish,25.406216,13.326550,13.286170,13.258051,13.203300,13.258051,53.993051,0.294562,0.013944,71.222334,3.371450
2021-02-04,13.609332,13.618545,13.284144,13.476617,201340000,0.132715,0.334400,Bullish,39.687382,13.420810,13.344926,13.291506,13.219223,13.291506,56.029752,0.009213,0.192473,2.754936,57.557682
2021-02-05,13.536376,13.682039,13.491308,13.669838,169152000,0.133462,0.190731,Bearish,69.974054,13.459332,13.379735,13.314827,13.231660,13.314827,54.604032,0.012201,0.045068,6.396817,23.629129
2021-02-08,14.380719,14.415578,13.672079,13.672079,434624000,0.708641,0.743500,Bullish,95.311474,13.766461,13.561733,13.416341,13.276722,13.416341,65.534568,0.034859,0.000000,4.688526,0.000000
2021-02-09,14.205926,14.524640,14.165339,14.283114,287560000,0.077188,0.359300,Bearish,21.482840,13.912949,13.678859,13.491539,13.313161,13.491539,62.195878,0.241526,0.040587,67.221115,11.296045
2021-02-10,14.704909,14.845094,14.283859,14.405119,485352000,0.299790,0.561235,Bullish,53.416138,14.176936,13.865413,13.607098,13.367739,13.607098,67.315049,0.140184,0.121261,24.977829,21.606033
2021-02-11,15.189455,15.210869,14.865015,14.920043,450828000,0.269412,0.345854,Bullish,77.897550,14.514442,14.106148,13.757799,13.439179,13.757799,71.369424,0.021414,0.055028,6.191674,15.910776
2021-02-12,14.901119,15.229793,14.715617,14.989512,374756000,0.088393,0.514176,Bearish,17.191241,14.643335,14.250688,13.866687,13.496510,13.866687,66.113885,0.240280,0.185502,46.731187,36.077572
2021-02-16,15.268639,15.310719,14.889917,15.003708,321960000,0.264931,0.420803,Bullish,62.958440,14.851769,14.435770,14.000206,13.566005,14.000206,69.224697,0.042081,0.113791,10.000135,27.041424
2021-02-17,14.846089,15.162313,14.720595,15.110024,274756000,0.263934,0.441718,Bearish,59.751765,14.849876,14.510374,14.080766,13.616205,14.080766,62.159252,0.052290,0.125494,11.837805,28.410430
2021-02-18,14.769401,14.813472,14.516421,14.669802,233868000,0.099598,0.297051,Bullish,33.529024,14.823051,14.557469,14.146350,13.661428,14.146350,60.943500,0.044072,0.153381,14.836381,51.634595
2021-02-19,14.866508,15.116000,14.787078,14.964113,271724000,0.097606,0.328922,Bearish,29.674379,14.837536,14.613658,14.214937,13.708686,14.214937,61.958122,0.151887,0.079430,46.177215,24.148407
2021-02-22,14.298052,15.072427,14.267425,14.715367,325884000,0.417316,0.805002,Bearish,51.840328,14.657708,14.556275,14.222852,13.731799,14.222852,53.239014,0.357060,0.030627,44.355124,3.804548
2021-02-23,14.085164,14.181525,13.335688,14.018682,391780000,0.066482,0.845838,Bullish,7.859931,14.466860,14.470619,14.209739,13.745656,14.209739,50.379661,0.096361,0.682994,11.392425,80.747644
2021-02-24,14.440726,14.448446,13.700712,14.065989,448320000,0.374737,0.747733,Bullish,50.116422,14.458149,14.465184,14.231738,13.772914,14.231738,54.750834,0.007719,0.365277,1.032368,48.851209
2021-02-25,13.254017,14.316978,13.163134,13.989051,824436000,0.735034,1.153844,Bearish,63.703073,14.056772,14.244972,14.138622,13.752565,14.138622,41.584078,0.327927,0.090883,28.420407,7.876520
2021-02-26,13.659381,13.798818,13.307301,13.697227,500932000,0.037846,0.491516,Bearish,7.699934,13.924308,14.138501,14.092980,13.748910,14.092980,46.331853,0.101590,0.352080,20.668751,71.631315
2021-03-01,13.786119,13.869034,13.498778,13.819235,353184000,0.033116,0.370256,Bearish,8.944147,13.878245,14.074431,14.063755,13.750370,14.063755,47.761390,0.049799,0.287340,13.449955,77.605898

In [98]:
this can be used to compare columns 
ydf.shift()

SyntaxError: invalid syntax (135002856.py, line 1)

In [10]:
ydf['Low']

Ticker            NVDA
Date
2015-01-02    0.474754
2015-01-05    0.472118
2015-01-06    0.459416
2015-01-07    0.457259
2015-01-08    0.463730
...                ...
2025-12-23  182.677196
2025-12-24  186.362690
2025-12-26  187.770981
2025-12-29  185.683524
2025-12-30  186.702281

[2765 rows x 1 columns]

In [11]:
pip install nasdaq-data-link

Collecting nasdaq-data-linkNote: you may need to restart the kernel to use updated packages.

  Downloading Nasdaq_Data_Link-1.0.4-py2.py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: pandas>=0.14 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (2.2.3)
Requirement already satisfied: numpy>=1.8 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (2.4.6)
Requirement already satisfied: requests>=2.7.0 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (2.34.2)
Requirement already satisfied: inflection>=0.3.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (0.5.1)
Requirement already satisfied: python-dateutil in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (2.9.0.post0)
Requirement already satisfied: six in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (1.17.0)
Requirement already satisfied: more-itertools in C:\Users\mcm4g\anaconda3\Lib\site-packages (from nasdaq-data-link) (11.0.2)
Requirement already satisfied: pytz>=2020.1 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas>=0.14->nasdaq-data-link) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from pandas>=0.14->nasdaq-data-link) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.7.0->nasdaq-data-link) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.7.0->nasdaq-data-link) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.7.0->nasdaq-data-link) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\mcm4g\anaconda3\Lib\site-packages (from requests>=2.7.0->nasdaq-data-link) (2026.5.20)
Downloading Nasdaq_Data_Link-1.0.4-py2.py3-none-any.whl (28 kB)
Installing collected packages: nasdaq-data-link
Successfully installed nasdaq-data-link-1.0.4

In [36]:
import nasdaqdatalink as ndl

In [37]:
My_Nas_Key = "bp9V2Fn_MCJ8xEUxYS8p"

ndl.ApiConfig.api_key = My_Nas_Key

In [80]:
ndf

Price,Close,High,Low,Open,Volume,Candle_Body,Candle_range (price action),Bullish/Bearish,Total price action,Body %,5_EMA,10_EMA,20_EMA,50_EMA,200_EMA,RSI
Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,,,,,,,,,,,
Date,,,,,,,,,,,,,,,,
2015-01-02,0.482423,0.486018,0.474754,0.482423,113680000,0.000000,0.011264,Bearish,0.011264,0.000000,0.482423,0.482423,0.482423,0.482423,0.482423,NaN
2015-01-05,0.474275,0.483861,0.472118,0.482423,197952000,0.008148,0.011743,Bearish,0.011743,69.387800,0.479707,0.480942,0.481647,0.482104,0.481647,NaN
2015-01-06,0.459895,0.475473,0.459416,0.474994,197764000,0.015098,0.016057,Bearish,0.016057,94.029920,0.473103,0.477115,0.479575,0.481233,0.479575,NaN
2015-01-07,0.458697,0.467325,0.457259,0.463251,321808000,0.004553,0.010065,Bearish,0.010065,45.237879,0.468301,0.473766,0.477587,0.480349,0.477587,NaN
2015-01-08,0.475952,0.478828,0.463730,0.463970,283780000,0.011983,0.015098,Bullish,0.015098,79.364899,0.470852,0.474164,0.477431,0.480177,0.477431,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-23,199.407593,203.592718,196.990412,202.224317,113561800,2.816724,6.602306,Bearish,6.602306,42.662739,199.743683,196.414477,190.964749,186.173520,190.964749,64.645029
2026-04-24,208.027542,210.704415,199.577384,199.727219,214134400,8.300323,11.127031,Bullish,11.127031,74.596032,202.504969,198.525943,192.589777,187.030540,192.589777,71.498286
2026-04-27,216.357834,216.577579,207.138583,209.405930,187172400,6.951904,9.438996,Bullish,9.438996,73.650888,207.122591,201.768105,194.853401,188.180630,194.853401,76.282913
2026-04-28,212.921844,214.480026,207.957629,209.246136,180275400,3.675709,6.522397,Bullish,6.522397,56.355182,209.055675,203.796058,196.574205,189.150874,196.574205,70.989367
2026-04-29,209.006409,212.472370,207.338355,212.452389,123711800,3.445981,5.134016,Bearish,5.134016,67.120571,209.039253,204.743394,197.758225,189.929522,197.758225,65.418380